# Generated by Django 2.2.5 on 2019-09-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.Realtor')),
            ],
        ),
    ]
